name: coderec
channels:
  - pytorch
  - anaconda
  - conda-forge
  - intel
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - _py-xgboost-mutex=2.0=cpu_0
  - alsa-lib=1.2.6.1=h7f98852_0
  - aom=3.3.0=h27087fc_1
  - asttokens=2.0.5=pyhd8ed1ab_0
  - attr=2.5.1=h166bdaf_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - blas=1.0=mkl
  - blosc=1.21.1=h83bc5f7_3
  - bottle=0.12.18=py_0
  - bottleneck=1.3.4=py39hce1f21e_0
  - brotli=1.0.9=h166bdaf_7
  - brotli-bin=1.0.9=h166bdaf_7
  - brotlipy=0.7.0=py39hb9d737c_1004
  - bzip2=1.0.8=hb9a14ef_9
  - c-ares=1.18.1=h7f8727e_0
  - ca-certificates=2022.6.15=ha878542_0
  - cairo=1.16.0=ha61ee94_1011
  - certifi=2022.6.15=py39hf3d152e_0
  - cffi=1.15.0=py39hd667e15_1
  - charset-normalizer=2.1.0=pyhd8ed1ab_0
  - click=8.0.4=py39h06a4308_0
  - colorama=0.4.5=pyhd8ed1ab_0
  - cryptography=37.0.2=py39hd97740a_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cycler=0.11.0=pyhd8ed1ab_0
  - dbus=1.13.6=h5008d03_3
  - debugpy=1.6.0=py39h5a03fae_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=0.8.3=pyhd8ed1ab_0
  - expat=2.4.8=h27087fc_0
  - ffmpeg=4.4.2=habc3f16_0
  - fftw=3.3.8=nompi_hfc0cae8_1114
  - filelock=3.7.1=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.0=h8e229c2_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.33.3=py39hb9d737c_0
  - freeglut=3.2.2=h9c3ff4c_1
  - freetype=2.10.4=h0708190_1
  - future=0.18.2=py39hf3d152e_5
  - gettext=0.19.8.1=h73d1719_1008
  - giflib=5.2.1=h36c2ea0_2
  - glib=2.70.2=h780b84a_4
  - glib-tools=2.70.2=h780b84a_4
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.7.6=hf3e180e_5
  - graphite2=1.3.13=h58526e2_1001
  - gst-plugins-base=1.20.3=hf6a322e_0
  - gstreamer=1.20.3=hd4edc92_0
  - harfbuzz=4.4.1=hf9f4e7c_0
  - hdf5=1.12.1=h69dfa17_1
  - hmmlearn=0.2.7=py39hde0f152_0
  - huggingface_hub=0.8.1=pyhd8ed1ab_0
  - icu=70.1=h27087fc_0
  - idna=3.3=pyhd8ed1ab_0
  - imageio=2.9.0=pyhd3eb1b0_0
  - imageio-ffmpeg=0.4.7=pyhd8ed1ab_0
  - importlib-metadata=4.11.4=py39hf3d152e_0
  - importlib_metadata=4.11.4=hd8ed1ab_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - intelpython=2022.1.0=0
  - ipykernel=6.13.1=py39hef51801_0
  - ipython=8.4.0=py39hf3d152e_0
  - jack=1.9.18=h8c3723f_1002
  - jasper=2.0.33=ha77e612_0
  - jedi=0.18.1=py39hf3d152e_1
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9e=h166bdaf_1
  - json-c=0.16=hc379101_0
  - jupyter_client=7.0.6=pyhd8ed1ab_0
  - jupyter_core=4.10.0=py39hf3d152e_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.2=py39h295c915_0
  - krb5=1.19.3=h3790be6_0
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h9c3ff4c_0
  - libblas=3.9.0=12_linux64_mkl
  - libbrotlicommon=1.0.9=h166bdaf_7
  - libbrotlidec=1.0.9=h166bdaf_7
  - libbrotlienc=1.0.9=h166bdaf_7
  - libcap=2.64=ha37c62d_0
  - libcblas=3.9.0=12_linux64_mkl
  - libclang13=14.0.6=default_h3a83d3e_0
  - libcups=2.3.3=hf5a7f15_1
  - libcurl=7.80.0=h0b77cf5_0
  - libdb=6.2.32=h9c3ff4c_0
  - libdeflate=1.12=h166bdaf_0
  - libdrm=2.4.111=h166bdaf_0
  - libedit=3.1.20210910=h7f8727e_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.10=h9b69904_4
  - libffi=3.4.2=h7f98852_5
  - libflac=1.3.4=h27087fc_0
  - libgcc-ng=12.1.0=h8d9b700_16
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libglib=2.70.2=h174f98d_4
  - libglu=9.0.0=he1b5a44_1001
  - libiconv=1.16=h516909a_0
  - libidn2=2.3.2=h7f98852_0
  - liblapack=3.9.0=12_linux64_mkl
  - liblapacke=3.9.0=12_linux64_mkl
  - libllvm14=14.0.6=he0ac6c6_0
  - libnghttp2=1.46.0=hce63b2e_0
  - libnsl=2.0.0=h7f98852_0
  - libogg=1.3.4=h7f98852_1
  - libopencv=4.5.5=py39hd011c1b_12
  - libopus=1.3.1=h7f98852_1
  - libpciaccess=0.16=h516909a_0
  - libpng=1.6.37=h21135ba_2
  - libpq=14.4=hd77ab85_0
  - libprotobuf=3.20.1=h6239696_0
  - libsndfile=1.0.31=h9c3ff4c_1
  - libsodium=1.0.18=h36c2ea0_1
  - libssh2=1.9.0=h4b1ad09_1
  - libstdcxx-ng=12.1.0=ha89aaad_16
  - libtasn1=4.18.0=h166bdaf_1
  - libtiff=4.4.0=hc85c160_1
  - libtool=2.4.6=h9c3ff4c_1008
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.32.1=h7f98852_1000
  - libva=2.15.0=h166bdaf_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libvpx=1.11.0=h9c3ff4c_3
  - libwebp=1.2.2=h3452ae3_0
  - libwebp-base=1.2.2=h7f98852_1
  - libxcb=1.13=h7f98852_1004
  - libxgboost=1.5.1=cpu_h3d145d1_2
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.14=h22db469_3
  - libzlib=1.2.12=h166bdaf_1
  - llvm-openmp=14.0.4=he0ac6c6_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - lzo=2.10=h309b0be_6
  - matplotlib-base=3.5.2=py39h700656a_0
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.1=py39hd3c417c_0
  - mkl_random=1.2.2=py39h51133e4_0
  - mock=4.0.3=pyhd3eb1b0_0
  - moviepy=1.0.3=pyhd8ed1ab_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=8.0.29=haf5c9bc_1
  - mysql-libs=8.0.29=h28c427c_1
  - ncurses=6.3=h7f8727e_2
  - nest-asyncio=1.5.5=pyhd8ed1ab_0
  - nettle=3.8=hc379101_0
  - ninja=1.11.0=h924138e_0
  - nltk=3.7=pyhd3eb1b0_0
  - nspr=4.32=h9c3ff4c_1
  - nss=3.78=h2350873_0
  - numexpr=2.8.1=py39h6abb31d_0
  - olefile=0.46=pyh9f0ad1d_1
  - opencv=4.5.5=py39hf3d152e_12
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1q=h166bdaf_0
  - p11-kit=0.24.1=hc5aa10d_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.4.2=py39h295c915_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pcre=8.45=h9c3ff4c_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.2.0=py39hae2aec6_0
  - pip=21.2.4=py39h06a4308_0
  - pixman=0.40.0=h36c2ea0_0
  - portalocker=2.3.0=py39h06a4308_0
  - portaudio=19.6.0=h57a0ea0_5
  - proglog=0.1.9=py_0
  - prompt-toolkit=3.0.29=pyha770c72_0
  - psutil=5.9.1=py39hb9d737c_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pulseaudio=14.0=h583eb01_5
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - py-opencv=4.5.5=py39hef51801_12
  - py-xgboost=1.5.1=cpu_py39h4655687_2
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.12.0=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pysocks=1.7.1=py39hf3d152e_5
  - pytables=3.7.0=py39h9da3b7f_0
  - python=3.9.13=h9a8a25e_0_cpython
  - python-crfsuite=0.9.8=py39hf939315_1
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytorch=1.12.0=py3.9_cuda11.3_cudnn8.3.2_0
  - pytorch-mutex=1.0=cuda
  - pytz=2021.3=pyhd3eb1b0_0
  - pyyaml=6.0=py39hb9d737c_4
  - pyzmq=19.0.2=py39hb69f2a1_2
  - qt-main=5.15.4=ha5833f6_2
  - readline=8.1.2=h7f8727e_1
  - regex=2022.3.15=py39h7f8727e_0
  - requests=2.28.1=pyhd8ed1ab_0
  - sacremoses=0.0.53=pyhd8ed1ab_0
  - scipy=1.7.3=py39hc147768_0
  - sentence-transformers=2.2.2=pyhd8ed1ab_0
  - sentencepiece=0.1.96=py39hf939315_1
  - setuptools=61.2.0=py39h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sklearn-crfsuite=0.3.6=pyh9f0ad1d_0
  - snappy=1.1.9=hbd366e4_1
  - sqlite=3.39.0=h4ff8645_0
  - stack_data=0.2.0=pyhd8ed1ab_0
  - svt-av1=1.1.0=h27087fc_1
  - tabulate=0.8.10=pyhd8ed1ab_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.12=h1ccaba5_0
  - tokenizers=0.12.1=py39h3045328_1
  - torchdata=0.4.0=py39
  - torchtext=0.6.0=py_1
  - torchvision=0.13.0=py39_cu113
  - tornado=6.1=py39hb9d737c_3
  - tqdm=4.64.0=pyhd8ed1ab_0
  - traitlets=5.2.2.post1=pyhd8ed1ab_0
  - transformers=4.18.0=py39h06a4308_0
  - typing-extensions=4.3.0=hd8ed1ab_0
  - typing_extensions=4.3.0=pyha770c72_0
  - tzdata=2022a=hda174b7_0
  - unicodedata2=14.0.0=py39hb9d737c_1
  - urllib3=1.26.9=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - wheel=0.37.1=pyhd3eb1b0_0
  - x264=1!161.3030=h7f98852_1
  - x265=3.5=h924138e_3
  - xcb-util=0.4.0=h166bdaf_0
  - xcb-util-image=0.4.0=h166bdaf_0
  - xcb-util-keysyms=0.4.0=h166bdaf_0
  - xcb-util-renderutil=0.3.9=h166bdaf_0
  - xcb-util-wm=0.4.1=h166bdaf_0
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-inputproto=2.3.2=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h7f8727e_1
  - yaml=0.2.5=h7f98852_2
  - zeromq=4.3.4=h9c3ff4c_1
  - zipp=3.8.0=pyhd8ed1ab_0
  - zlib=1.2.12=h166bdaf_1
  - zstd=1.5.2=h8a70e8d_2
  - pip:
    - absl-py==1.2.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - astunparse==1.6.3
    - async-timeout==4.0.2
    - attrs==22.1.0
    - cachetools==5.2.0
    - datasets==2.4.0
    - dill==0.3.5.1
    - et-xmlfile==1.1.0
    - flatbuffers==1.12
    - frozenlist==1.3.1
    - fsspec==2022.7.1
    - gast==0.4.0
    - google-auth==2.9.1
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.47.0
    - h5py==3.7.0
    - hmmviz==0.0.7
    - keras==2.9.0
    - keras-preprocessing==1.1.2
    - libclang==14.0.1
    - markdown==3.4.1
    - markupsafe==2.1.1
    - multidict==6.0.2
    - multiprocess==0.70.13
    - numpy==1.22.4
    - oauthlib==3.2.0
    - openai==0.22.1
    - openpyxl==3.0.10
    - opt-einsum==3.3.0
    - pandas-stubs==1.4.3.220801
    - prettytable==3.3.0
    - protobuf==3.19.4
    - pyarrow==9.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyhhmm==2.0.1
    - requests-oauthlib==1.3.1
    - responses==0.18.0
    - rsa==4.9
    - scikit-learn==0.23.2
    - seaborn==0.11.2
    - tenacity==8.0.1
    - tensorboard==2.9.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.9.1
    - tensorflow-estimator==2.9.0
    - tensorflow-io-gcs-filesystem==0.26.0
    - termcolor==1.1.0
    - tree-sitter==0.20.0
    - types-pytz==2022.1.2
    - werkzeug==2.2.1
    - wrapt==1.14.1
    - xxhash==3.0.0
    - yarl==1.8.1
